### ISSUE TITLE
Dark Theme affecting color swatches in Google Docs

### ISSUE THREAD

**Issue by TexturedGuppy** [liorgrossman/darkness#199] opened 2019-12-18 15:20 UTC
* Site: googledocs
* Theme: iceberg
* URL: https://docs.google.com/document/d/1rWDPoVwGgtFnRiXVwHsBjK27B-tkOaMh648HccUdiQU/edit#
* Darkness Version: 2.0.25 Pro
* Browser: Chrome 79.0.3945.79
* Operating System: Windows 10
* Resolution: 1920x1080
* Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36

**Bug Description**
When choosing a new text color, all of the colors are visually incorrect, could be a simple fix by applying the css differently to that div. In the screenshot I am hovering over the red swatch that is actually cyan.

**Screenshots**
![tempsnip](https://user-images.githubusercontent.com/22183213/71098574-ebde5080-217f-11ea-918e-8182a4454a51.png)

**Comment by theme1256** [comment] 2019-12-20 10:33
Duplicate of #198

**Closed by theme1256** 2019-12-20 10:33 UTC
Labels: bug, duplicate
