### ISSUE TITLE
Add options to customise the skins

### ISSUE THREAD

**Issue by lukeflegg** [liorgrossman/darkness#143] opened 2019-02-05 11:57 UTC
I'd love to be able to customise anything.
The 'out of the box' skins are nice, but it would be a game changer if you could allow certain shades to be adjusted, or elements.

Eg. just now, I'm kinda impressed by how - in Google Docs - the white page is darkened only where there is no content on the page of the document, but I actually would like the option to disable that element in the theme as it's quite unusual visually.

**Comment by liorgrossman** [comment] 2019-02-05 16:53
Hi Luke.
Thanks for the idea, I'd love to hear your thought on how could specific elements be adjusted.
Doing so with code (CSS) is one thing, doing so without code (UI-based editor) is extremely complex to develop, I'm not sure it's feasible.
In any case, I think this is a duplicate of #86 so I'm closing this issue, please add your thoughts on #86.
Thanks!

**Closed by liorgrossman** 2019-02-05 16:53 UTC
Labels: suggestion
