### ISSUE TITLE
Darkness on FB to wide

### ISSUE THREAD

**Issue by Falcho** [liorgrossman/darkness#92] opened 2018-11-27 10:24 UTC
When using darkness themes on Facebook, it widens the page so theres a scroll bar on the bottom of the page, making it hard to see you chat boxes. https://imgur.com/a/2P8bluF

And the top Facebook bar doesn't follow down when you scroll down either

would be awesome if it fixxed so that the bottom line scroll bar doesnt pop up when you are using a theme, and the top Facebook bar would follow when you scroll down

**Comment by theme1256** [comment] 2018-11-28 13:03
I dont have this problem, could you send us a list of your plugins, so that we might be able to re-create the issue?

**Comment by Falcho** [comment] 2018-11-28 14:57
The plugins i have is Adblock plus, Adblock for Youtube and CR-Unblocker
Hope this will help, very nice plugin otherwise!

Den ons. 28. nov. 2018 kl. 14.03 skrev Folkmann <notifications@github.com>:

**Comment by liorgrossman** [comment] 2018-11-29 18:15
Can't reproduce the scroll bar either.
Can you please go to https://www.whatsmybrowser.org/ and send us your system info? (browser, resolution, etc.)

**Comment by Falcho** [comment] 2018-11-30 13:40
here it is whatsmybrowser.org/b/M7DQG2F

Den tor. 29. nov. 2018 kl. 19.15 skrev Lior Grossman <
notifications@github.com>:

**Comment by liorgrossman** [comment] 2018-12-26 23:13
Unfortunately, I wasn't able to reproduce this problem either, or to figure out what might be the source.
No other Darkness user has ever reported such problem yet, so I assume it's very configuration-specific. For example, this might be due to other browser extensions conflicting with Darkness, so I'd suggest disabling other extensions and trying again.
Unfortunately, without the ability to reproduce this issue, we won't be able to solve it. Closing this for now.

**Closed by liorgrossman** 2018-12-26 23:13 UTC
Labels: bug
