### ISSUE TITLE
Facebook objects and chat not scrolling in Mozilla

### ISSUE THREAD

**Issue by Gianfredo** [liorgrossman/darkness#126] opened 2019-01-09 23:39 UTC
**Bug Information**
(visit the affected website → click the moon icon → "Send Feedback" → "Bug Report" → paste here)
* Site: facebook
* Theme: material
* URL: https://www.facebook.com/IlMartirio/?ref=bookmarks
* Darkness Version: 2.0.4 Pro
* Browser: Firefox 64.0
* Operating System: Mac OS X 10.14
* Resolution: 1366x768
* Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0

**Bug Description**
Please provide a clear description of what the bug or issue is.
When I scroll down F
![screenshot 2019-01-10 at 00 39 21](https://user-images.githubusercontent.com/45300423/50936497-359ec100-1470-11e9-9324-3427e8863a93.png)
acebook objects and chat don't scroll and fly to top of page in Mozilla
**Screenshots**
If necessary, add screenshots to help explain your problem.

**Comment by liorgrossman** [comment] 2019-01-09 23:50
I'm closing this issue, as it is a duplicate of this bug report: https://github.com/liorgrossman/darkness/issues/81

**Closed by liorgrossman** 2019-01-09 23:50 UTC
