### ISSUE TITLE
messenger stays in the same place relative to scroll

### ISSUE THREAD

**Issue by Thorleyfo** [liorgrossman/darkness#132] opened 2019-01-20 12:45 UTC

**Comment by theme1256** [comment] 2019-01-20 16:53
I guess that this is a duplicate of #81.  
You have to give us more info, otherwise, we won't know what to fix.

**Comment by theme1256** [comment] 2019-02-01 21:35
Im closing this issue, because there is has been no reply and it's assumed to be a duplicate.

**Closed by theme1256** 2019-02-01 21:35 UTC
