### ISSUE TITLE
Facebook pages left and right bleed hang up

### ISSUE THREAD

**Issue by kevkev771** [liorgrossman/darkness#102] opened 2018-12-08 12:38 UTC
on the Facebook page no matter what topic one uses the left side and the right side do not go down with the middle ghet down then it is left and right black and not like in the standard right friend list and left favorites, info, groups. That's only with Fierfox.

**Comment by liorgrossman** [comment] 2018-12-08 23:13
Thanks for the feedback!
The is a duplicate of this bug: https://github.com/liorgrossman/darkness/issues/81
This "fixed" sidebar/toolbar happens on Firefox only, still haven't managed to figure how to solve this. Any idea @theme1256 @TheGooner93 ?

**Comment by TheGooner93** [comment] 2018-12-11 03:14
Hi @liorgrossman , this is some weird behavior! Let me have a look and I'll try to update you soon.

**Comment by theme1256** [comment] 2018-12-11 18:05
A quick stab at google reveals that FF 52 has a problem with `position: fixed` and the reasons are plenty: [StackOverflow has this to say](https://stackoverflow.com/questions/21440604/css-position-fixed-acting-like-absolute-in-firefox).
Don't know if that gets any of you closer to a solution, I'm having trouble compiling the FF version, so it'll be a bit before I can help.

**Comment by liorgrossman** [comment] 2018-12-11 20:07
Thanks!
There's an issue in Firefox' bug tracker, but they say it's the intended behavior according to the spec: https://bugzilla.mozilla.org/show_bug.cgi?id=1311070
I assume this is not going to be fixed, so we would need to find a workaround.
Since this is a duplicate, I'm closing this issue, let's discuss future solutions on https://github.com/liorgrossman/darkness/issues/81
P.S. LMK if you need a hand running Darkness on FF, should work fluently with `gulp ff`.

**Closed by liorgrossman** 2018-12-11 20:07 UTC
Labels: duplicate
