### ISSUE TITLE
Framerate drops while playing Videos at 1080p

### ISSUE THREAD

**Issue by TheChicagoMike** [liorgrossman/darkness#108] opened 2018-12-11 21:50 UTC
**Bug Information**
(visit the affected website → click the moon icon → "Send Feedback" → "Bug Report" → paste here)
* Site: Facebook.com
* Theme: Iceberg
* URL: https://www.facebook.com/gaming/StoneMountain64/?video_id=276207276372426&external_ref=live_notification&notif_id=1544562778001098&notif_t=live_video_explicit&ref=notif
* Darkness Version: Free/Trial
* Browser: Google Chrome
* Operating System: Windows 7 (64-Bit)

**Bug Description**
Videos playing at 1080p without the theme play smooth and have no stutter.
Videos playing at 1080p "WITH" the theme are choppy, stutter constant and drops in framerate are extremely noticeable to the point I don't want to use the theme at all. 

**Screenshots**
If necessary, add screenshots to help explain your problem.

**Comment by theme1256** [comment] 2019-02-08 20:27
I can't reproduce this.

Perhaps my machine has a bit to much power.  
I often experience slowdown when using dark-type plugins.

**Comment by liorgrossman** [comment] 2019-02-09 03:10
Neither am I - I don't see any drop in framerate, both in regular mode and in full-screen.
I'm on a 2013 13" MacBook Pro, which isn't particularly strong, surely in terms of graphics (simple Intel Iris graphic chip).
I suspect this problem is machine specific, so unfortunately we won't be unable to debug it.
Closing this ticket for now.

**Closed by liorgrossman** 2019-02-09 03:10 UTC
Labels: bug
